security:
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        in_memory: { memory: ~ }
        pdo:
            entity:
                class: App\Entity\User
                property: login
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            entry_point: App\Security\AuthenticationEntryPoint
            anonymous: true
            provider: pdo
            json_login:
                check_path: /api/security/login
            logout:
                path: /api/security/logout
    access_control:
